---
title: "Toetsweb MocUp"
author: "Klinkenberg"
date: '2022-04-28'
output:
  html_document:
    toc            : TRUE
    self_contained : false
    toc_float:
      collapsed    : FALSE
      smooth_scroll: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("shiny")
library("stringr")
all.answer.options <- readxl::read_excel("answers.xlsx", sheet = "answerOptions")
fase.select        <- readxl::read_excel("answers.xlsx", sheet = "fase")

question.position = "In welke beschrijving herken je jouw opleiding nu het meest?"
question.ambition = "Welke beschrijving past over 2 jaar het beste bij jouw opleiding?"
```

```{js}
var positie = [...Array(5)].map(x=>Array(3).fill(0));  
var ambitie = [...Array(5)].map(x=>Array(3).fill(0)) ;  

function myFunction(x, y) {
  for (var i = 0; i <= 3; i++) {
    var score;
  
    if (document.getElementsByName(x)[i].checked) {
    
    score = document.getElementsByName(x)[i].value;
    
    document.getElementById(y).innerHTML = score;
    
    if (x.split("")[3] == "p") { positie[ x.split("")[1]-1 ][ x.split("")[2]-1 ] = score 
                                 faseSelect( Number(positie[ x.split("")[1]-1 ][ 0 ]), 
                                             Number(positie[ x.split("")[1]-1 ][ 1 ]), 
                                             Number(positie[ x.split("")[1]-1 ][ 2 ]), 
                                             faseSelectId, faseId, " "+x.split("")[1]+"o " )
                               }
    if (x.split("")[3] == "a") { ambitie[ x.split("")[1]-1 ][ x.split("")[2]-1 ] = score 
                                 faseSelect( Number(ambitie[ x.split("")[1]-1 ][ 0 ]), 
                                             Number(ambitie[ x.split("")[1]-1 ][ 1 ]), 
                                             Number(ambitie[ x.split("")[1]-1 ][ 2 ]), 
                                             faseSelectId, faseId, " "+x.split("")[1]+"ao " )
                               }
    
    // console.log(splitted.join(""));
    
    }
  }
}

function myInput(input, output){
var y = document.getElementById(input).value;
  document.getElementById(output).innerHTML = y;    
}

function faseSelect(kwaliteitscriteriaScore, ontwerpScore, borgingScore, faseSelectId, faseId, target) {
  
  concat = '' + kwaliteitscriteriaScore + ontwerpScore + borgingScore
  
  var result = 0;
  
  for (var i = 0; i < faseSelectId.length; i++) {
  
       if (concat == faseSelectId[i]) { result = faseId[i] }
  }
  
  // console.log(concat);
  // console.log(result);
  
  document.getElementById(target).innerHTML = result; 
  
}
```

```{r, results='asis'}
cat("<script>\n\n")

cat('var faseSelectId = [',paste0(fase.select$faseSelectId, sep=","), ']\n\n')
cat('var faseId       = [',paste0(fase.select$faseId,       sep=","), ']\n\n')

cat("</script>")
```

# Toetsweb

```{js}
faseSelect(4, 4, 4, faseSelectId, faseId, "test")
```

Web image here + info popup

```{css}
.part:hover {
   fill: red;
   cursor: pointer;
}
```


```{r, child="Toetsmodel.svg"}
```




# Start scan

```{r, results ='asis'}
entiteit = 1:5
element = 1:3

# ent = 2
# el  = 1

for(ent in 1:length(entiteit)) {

  for(el in 1:length(element)) {
    
# options <- subset(all.answer.options, entiteit.id == ent & element.id == el)

options <- all.answer.options[which(all.answer.options$entiteit.id == ent & all.answer.options$element.id == el),]


if(el == 1) { cat("##", options$entiteit.naam[1],"\n\n") }

cat("###", options$element.naam[1]," - positie \n\n")

# radioButtons(inputId      = paste0(ent,el,"p"), 
#              label        = question.position,
#              selected     = 0, 
#              choiceNames  = options$fase.option, 
#              choiceValues = options$fase.score
#              )

cat('<div id="',paste0(ent,el,"p"),'" class="form-group shiny-input-radiogroup shiny-input-container" role="radiogroup" aria-labelledby="21p-label" onchange="myFunction(\'',paste0(ent,el,"p"),'\', \'',paste0(ent,el,"o"),'\')">\n')
cat('<label class="control-label" id="',paste0(ent,el,"p"),'-label" for="',paste0(ent,el,"p"),'">',question.position,'</label>\n')
cat('<div class="shiny-options-group">\n')

for (opt in 1:4) {
  cat('<div class="radio">\n<label>\n')
  cat('<input type="radio" name="',paste0(ent,el,"p"),'" value="',options$fase.score[opt],'">')
  cat('<span>',options$fase.option[opt],'</span>\n</label>\n</div>')
}

cat('</div>\n</div>')

cat('<textarea id="',paste0(ent,el,"p","txt"),'" name="w3review" rows="4" cols="115" oninput="myInput(\'',paste0(ent,el,"p","txt"),'\', \'',paste0(ent,el,"potxt"),'\' )">Licht dit antwoord toe.</textarea>')

cat("\n\n###", options$element.naam[1]," - ambitie \n\n")

# radioButtons(paste0(ent,el,"a"), question.ambition,
#              selected     = 0, 
#              choiceNames  = options$fase.option, 
#              choiceValues = options$fase.score
#              )

cat('<div id="',paste0(ent,el,"a"),'" class="form-group shiny-input-radiogroup shiny-input-container" role="radiogroup" aria-labelledby="21p-label" onchange="myFunction(\'',paste0(ent,el,"a"),'\', \'',paste0(ent,el,"ao"),'\')">\n')
cat('<label class="control-label" id="',paste0(ent,el,"a"),'-label" for="',paste0(ent,el,"a"),'">',question.ambition,'</label>\n')
cat('<div class="shiny-options-group">\n')

for (opt in 1:4) {
  cat('<div class="radio">\n<label>\n')
  cat('<input type="radio" name="',paste0(ent,el,"a"),'" value="',options$fase.score[opt],'">')
  cat('<span>',options$fase.option[opt],'</span>\n</label>\n</div>')
}

cat('</div>\n</div>')

cat('<textarea id="',paste0(ent,el,"a","txt"),'" name="w3review" rows="4" cols="115" oninput="myInput(\'',paste0(ent,el,"a","txt"),'\', \'',paste0(ent,el,"aotxt"),'\' )">Licht dit antwoord toe.</textarea>')

  }
}
```

# Report

<button type="button">Download</button>

## Visual


### Positie

```{r, results='asis'}
# entiteiten <- unique(all.answer.options$entiteit.naam)

cat('<table class="table">\n')
cat("<td>Toetsweb</td><td>Kwaliteitscriteria</td><td>Ontwerp</td><td>Borging</td><td>Fase</td>\n")

for(ent in 1:length(entiteit)) {

  cat("<tr>\n")
  cat("<td>", unique(all.answer.options$entiteit.naam)[ent], "</td>\n")
  
  for(el in 1:3) {
    
    cat("<td id='",paste0(ent,el,"o"),"'>")
    cat("</td>\n")
 
  }
  
  cat('<td id="',paste0(ent,"o"),'">')
  cat("fase advies")
  cat("</td>")
  cat("</tr>\n")
  
}

cat("</table>\n")
```

### Ambitie

```{r, results='asis'}
# entiteiten <- unique(all.answer.options$entiteit.naam)

cat('<table class="table">\n')
cat("<td>Toetsweb</td><td>Kwaliteitscriteria</td><td>Ontwerp</td><td>Borging</td><td>Fase</td>\n")

for(ent in 1:length(entiteit)) {

  cat("<tr>\n")
  cat("<td>", unique(all.answer.options$entiteit.naam)[ent], "</td>\n")
  
  for(el in 1:3) {
    
    cat("<td id='",paste0(ent,el,"ao"),"'>")
    cat("</td>\n")
 
  }
  
  cat("<td id='",paste0(ent,"ao"),"'>")
  cat("fase projectie")
  cat("</td>")
  cat("</tr>\n")
  
}

cat("</table>\n")
```

## Textual

```{r, results='asis'}
# entiteiten <- unique(all.answer.options$entiteit.naam)

for(ent in 1:length(entiteit)) {

  cat("<h3>", unique(all.answer.options$entiteit.naam)[ent], "</h3>\n")
  
  for(el in 1:3) {
    
    cat("<p id='",paste0(ent,el,"potxt"),"'></p>\n\n")
    cat("<p id='",paste0(ent,el,"aotxt"),"'></p>\n\n")
 
  }
  
  cat("<p id='",paste0(ent,"otxt"),"'>")
  cat("</p>")
  
}
```