version: "3.9"

services:
    meldkamercoach:
        image: gitlab.theburo.nl:5050/pieterbikkel/toetsweb:master
        container_name: toetsweb
        networks:
            - proxy
        labels:
            traefik.enable: "true"
            traefik.http.routers.toetsweb.entrypoints: "https"
            traefik.http.routers.toetsweb.rule: "Host(`toetsweb.acc2.theburo.nl`)"
            traefik.http.routers.toetsweb.tls: "true"
            traefik.http.routers.toetsweb.tls.certresolver: "http"
            traefik.docker.network: "proxy"

networks:
  proxy:
    external: true
